# Site settings
title: æˆ‘æ˜¯é™ˆğŸ‘
header-img: img/home-bg.jpg
email: cywhoyi@gmail.com
description: â€œäººç”Ÿåœ¨ä¸–ï¼Œä½“éªŒä¸ä¸€æ ·çš„ç”Ÿæ´»æ–¹å¼!â€
baseurl:
url: "http://cywhoyi.iteye.com"
twitter_username: chenyang1987
github_username:  IBYoung
facebook_username:  IBYoung

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
